version: '3.8'
services:

  traefik:
    image: programic/traefik:latest
    command:
      - "--certificatesresolvers.lets-encrypt.acme.email=certs@domain.tld"
      - "--providers.docker.network=web"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/data

networks:
  web:
    external: true

volumes:
  traefik-data: