version: '3.8'
services:

  traefik:
    image: programic/traefik:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]

    # If you use TransIP as a resolver
    environment:
      TRANSIP_ACCOUNT_NAME: <your-transip-account-name-here>
      TRANSIP_PRIVATE_KEY_PATH: /run/secrets/transip-private-key
    secrets:
      - transip-private-key

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/data

networks:
  web:
    external: true

volumes:
  traefik-data:

# If you use TransIP as a resolver
secrets:
  transip-private-key:
    external: true