version: '3.8'
services:

  traefik:
    image: traefik:v2.9
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]

    # Optional if dnsChallenge with TransIP
    environment:
      TRANSIP_ACCOUNT_NAME: <your-transip-account-name-here>
      TRANSIP_PRIVATE_KEY_PATH: /run/secrets/transip-private-key
    secrets:
      - transip-private-key

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
      - ./config/dynamic:/dynamic
      - ./data:/data

networks:
  web:
    external: true

# Optional if dnsChallenge with TransIP
secrets:
  transip-private-key:
    external: true