[providers.file]
  directory = "/dynamic"
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
[api]
  insecure = true
[certificatesResolvers.lets-encrypt.acme]
  storage = "/data/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]
[providers.docker]
  watch = true
  exposedByDefault = false
  swarmMode = true