[http.middlewares]
  [http.middlewares.to-https.redirectScheme]
    scheme = "https"
  [http.middlewares.secure-headers.headers]
    contentSecurityPolicy = "frame-ancestors 'self'"
    sslredirect = true
    contenttypenosniff = true
    browserxssfilter = true
    stsincludesubdomains = true
    stspreload = true
    stsseconds = 31536000
    referrerpolicy = "same-origin"
    [http.middlewares.secure-headers.headers.customResponseHeaders]
      server = ""
[http.middlewares.maintenance]
  [http.middlewares.maintenance.plugin]
    [http.middlewares.maintenance.plugin.maintenance]
      informInterval = 60
      informTimeout = 5
      informUrl = "https://maintenance.programic.com/inform.json"